from sqlalchemy import Column, Integer, String, Text, DateTime, Date, ForeignKey, Numeric
from sqlalchemy.orm import relationship

from database import Base


class Tickers(Base):
    __tablename__ = 'tickers'

    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), unique=True, nullable=False)
    name = Column(String(100), nullable=False)
    industry_code = Column(String(100), nullable=False)
    industry = Column(String(100), nullable=False)
    modified_at = Column(DateTime, nullable=True)

class IncomeStatements(Base):
    __tablename__ = 'income_statements'

    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), unique=False, nullable=False)
    total_revenue = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    operating_revenue = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    cost_of_revenue = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    gross_profit = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    operating_expense = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    selling_general_and_administrative = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    general_and_administrative_expense = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    selling_and_marketing_expense = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_general_and_administrative = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    research_and_development = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    operating_income = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_non_operating_interest_income_expense = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    interest_income_non_operating = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    interest_expense_non_operating = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_other_finance_cost = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_income_expense = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    gain_on_sale_of_security = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_non_operating_income_expenses = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    pretax_income = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    tax_provision = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_income_common_stockholders = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_income = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_income_including_noncontrolling_interests = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_income_continuous_operations = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    average_dilution_earnings = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    diluted_ni_available_to_come_stockholders = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    basic_eps = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    diluted_eps = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    basic_average_shares = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    diluted_average_shares = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_operating_income_as_reported = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_expenses = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_income_from_continuing_and_discontinued_operation = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    normalized_income = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    interest_income = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    interest_expense = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_interest_income = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    ebit = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    ebitda = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    reconciled_cost_of_revenue = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    reconciled_depreciation = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_income_from_continuing_operation_net_minority_interest = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_unusual_items_excluding_goodwill = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_unusual_items = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    normalized_ebitda = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    tax_rate_for_calcs = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    tax_effect_of_unusual_items = Column(Numeric(precision=30, scale=10), default=0, nullable=False)

    modified_at = Column(DateTime, nullable=True)

class BalanceSheets(Base):
    __tablename__ = 'balance_sheets'

    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), unique=False, nullable=False)

    treasury_shares_number = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    ordinary_shares_number = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    share_issued = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_debt = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    tangible_book_value = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    invested_capital = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    working_capital = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_tangible_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    capital_lease_obligations = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    common_stock_equity = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_capitalization = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_equity_gross_minority_interest = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    stockholders_equity = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    gains_losses_not_affecting_retained_earnings = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_equity_adjustments = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    retained_earnings = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    additional_paid_in_capital = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    capital_stock = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    common_stock = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_liabilities_net_minority_interest = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_non_current_liabilities_net_minority_interest = Column(Numeric(precision=30, scale=10), default=0,
                                                                 nullable=False)
    other_non_current_liabilities = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    tradeand_other_payables_non_current = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    long_term_debt_and_capital_lease_obligation = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    long_term_capital_lease_obligation = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    long_term_debt = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    current_liabilities = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_current_liabilities = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    current_debt_and_capital_lease_obligation = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    current_capital_lease_obligation = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    pensionand_other_post_retirement_benefit_plans_current = Column(Numeric(precision=30, scale=10), default=0,
                                                                    nullable=False)
    payables_and_accrued_expenses = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    current_accrued_expenses = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    payables = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    dueto_related_parties_current = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_tax_payable = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    accounts_payable = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    total_non_current_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_non_current_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    investments_and_advances = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    investmentin_financial_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    available_for_sale_securities = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    goodwill_and_other_intangible_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_intangible_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    goodwill = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_ppe = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    accumulated_depreciation = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    gross_ppe = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    leases = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    construction_in_progress = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_properties = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    buildings_and_improvements = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    land_and_improvements = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    properties = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    current_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_current_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    receivables = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    accounts_receivable = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    cash_cash_equivalents_and_short_term_investments = Column(Numeric(precision=30, scale=10), default=0,
                                                              nullable=False)
    other_short_term_investments = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    cash_and_cash_equivalents = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    cash_equivalents = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    cash_financial = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    modified_at = Column(DateTime, nullable=True)

class Cashflows(Base):
    __tablename__ = 'cashflows'

    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), unique=False, nullable=False)

    free_cash_flow = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    repurchase_of_capital_stock = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    repayment_of_debt = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    issuance_of_debt = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    capital_expenditure = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    interest_paid_supplemental_data = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    income_tax_paid_supplemental_data = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    end_cash_position = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    beginning_cash_position = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    effect_of_exchange_rate_changes = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    changes_in_cash = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    financing_cash_flow = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    cash_flow_from_continuing_financing_activities = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_other_financing_charges = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_common_stock_issuance = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    common_stock_payments = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_issuance_payments_of_debt = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_long_term_debt_issuance = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    long_term_debt_payments = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    long_term_debt_issuance = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    investing_cash_flow = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    cash_flow_from_continuing_investing_activities = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_other_investing_changes = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_investment_purchase_and_sale = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    sale_of_investment = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    purchase_of_investment = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_business_purchase_and_sale = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    purchase_of_business = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_ppe_purchase_and_sale = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    sale_of_ppe = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    purchase_of_ppe = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    operating_cash_flow = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    cash_flow_from_continuing_operating_activities = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_working_capital = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_other_current_liabilities = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_other_current_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_payables_and_accrued_expense = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_accrued_expense = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_payable = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_account_payable = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_prepaid_assets = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    change_in_receivables = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    changes_in_account_receivables = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    other_non_cash_items = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    stock_based_compensation = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    asset_impairment_charge = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    deferred_tax = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    deferred_income_tax = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    depreciation_amortization_depletion = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    depreciation_and_amortization = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    net_income_from_continuing_operations = Column(Numeric(precision=30, scale=10), default=0, nullable=False)

    modified_at = Column(DateTime, nullable=True)

class Rawstatistics(Base):
    __tablename__ = 'rawstatistics'

    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), unique=False, nullable=False)
    modified_at = Column(Date, nullable=True)

    per = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    forward_per = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    pbr = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    roe = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    current_ratio = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    quick_ratio = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    averageVolume10days = Column(Numeric(precision=30, scale=10), default=0, nullable=False)

class Refinedstatistics(Base):
    __tablename__ = 'refinedstatistics'

    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), unique=False, nullable=False)
    modified_at = Column(Date, nullable=True)

    refined_per = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    refined_forward_per = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    refined_pbr = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    refined_roe = Column(Numeric(precision=30, scale=10), default=0, nullable=False)

    current_ratio = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    quick_ratio = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    averageVolume10days = Column(Numeric(precision=30, scale=10), default=0, nullable=False)

class Recommandationtickers(Base):
    __tablename__ = 'recommandationtickers'

    id = Column(Integer, primary_key=True)
    ticker = Column(String(10), unique=False, nullable=False)
    modified_at = Column(Date, nullable=True)

    recommandation_per = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    recommandation_forward_per = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    recommandation_pbr = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    recommandation_roe = Column(Numeric(precision=30, scale=10), default=0, nullable=False)

    current_ratio = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    quick_ratio = Column(Numeric(precision=30, scale=10), default=0, nullable=False)
    averageVolume10days = Column(Numeric(precision=30, scale=10), default=0, nullable=False)