"""empty message

Revision ID: 7f6b8b2fbd82
Revises: 5594eb057ca1
Create Date: 2024-03-13 03:48:16.612461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6b8b2fbd82'
down_revision: Union[str, None] = '5594eb057ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_statements', sa.Column('operating_expense', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('income_statements', sa.Column('selling_and_marketing_expense', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('income_statements', sa.Column('tax_provision', sa.Numeric(precision=30, scale=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_statements', 'tax_provision')
    op.drop_column('income_statements', 'selling_and_marketing_expense')
    op.drop_column('income_statements', 'operating_expense')
    # ### end Alembic commands ###
