"""empty message

Revision ID: 80901c81b0c7
Revises: 7f6b8b2fbd82
Create Date: 2024-03-14 17:09:13.465899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80901c81b0c7'
down_revision: Union[str, None] = '7f6b8b2fbd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('treasury_shares_number', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('ordinary_shares_number', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('share_issued', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('tangible_book_value', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('invested_capital', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_tangible_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('capital_lease_obligations', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('common_stock_equity', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('total_capitalization', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('total_equity_gross_minority_interest', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('stockholders_equity', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('gains_losses_not_affecting_retained_earnings', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_equity_adjustments', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('retained_earnings', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('additional_paid_in_capital', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('capital_stock', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('common_stock', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('total_liabilities_net_minority_interest', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('total_non_current_liabilities_net_minority_interest', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_non_current_liabilities', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('tradeand_other_payables_non_current', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('long_term_debt_and_capital_lease_obligation', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('long_term_capital_lease_obligation', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('long_term_debt', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('current_liabilities', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_current_liabilities', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('current_debt_and_capital_lease_obligation', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('current_capital_lease_obligation', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('pensionand_other_post_retirement_benefit_plans_current', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('payables_and_accrued_expenses', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('current_accrued_expenses', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('payables', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('dueto_related_parties_current', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('total_tax_payable', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('accounts_payable', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('total_non_current_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_non_current_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('investments_and_advances', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('investmentin_financial_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('available_for_sale_securities', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('goodwill_and_other_intangible_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_intangible_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('goodwill', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_ppe', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('gross_ppe', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('leases', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('construction_in_progress', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_properties', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('buildings_and_improvements', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('land_and_improvements', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('properties', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('current_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_current_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('receivables', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('accounts_receivable', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash_cash_equivalents_and_short_term_investments', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_short_term_investments', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash_and_cash_equivalents', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash_equivalents', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash_financial', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_sheets')
    # ### end Alembic commands ###
