"""empty message

Revision ID: 895eba321e75
Revises: 8eb7caba836f
Create Date: 2024-03-31 23:00:13.009047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '895eba321e75'
down_revision: Union[str, None] = '8eb7caba836f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawstatistics', sa.Column('current_ratio', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('rawstatistics', sa.Column('quick_ratio', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('recommandationtickers', sa.Column('recommandation_per', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('recommandationtickers', sa.Column('recommandation_forward_per', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('recommandationtickers', sa.Column('recommandation_pbr', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('recommandationtickers', sa.Column('recommandation_roe', sa.Numeric(precision=30, scale=10), nullable=False))
    op.drop_column('recommandationtickers', 'refined_roe')
    op.drop_column('recommandationtickers', 'refined_per')
    op.drop_column('recommandationtickers', 'refined_forward_per')
    op.drop_column('recommandationtickers', 'refined_pbr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommandationtickers', sa.Column('refined_pbr', mysql.DECIMAL(precision=30, scale=10), nullable=False))
    op.add_column('recommandationtickers', sa.Column('refined_forward_per', mysql.DECIMAL(precision=30, scale=10), nullable=False))
    op.add_column('recommandationtickers', sa.Column('refined_per', mysql.DECIMAL(precision=30, scale=10), nullable=False))
    op.add_column('recommandationtickers', sa.Column('refined_roe', mysql.DECIMAL(precision=30, scale=10), nullable=False))
    op.drop_column('recommandationtickers', 'recommandation_roe')
    op.drop_column('recommandationtickers', 'recommandation_pbr')
    op.drop_column('recommandationtickers', 'recommandation_forward_per')
    op.drop_column('recommandationtickers', 'recommandation_per')
    op.drop_column('rawstatistics', 'quick_ratio')
    op.drop_column('rawstatistics', 'current_ratio')
    # ### end Alembic commands ###
