"""empty message

Revision ID: 8eb7caba836f
Revises: fcd67441e201
Create Date: 2024-03-31 22:03:00.515194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb7caba836f'
down_revision: Union[str, None] = 'fcd67441e201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rawstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('per', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('forward_per', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('pbr', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('roe', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommandationtickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('refined_per', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('refined_forward_per', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('refined_pbr', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('refined_roe', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('current_ratio', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('quick_ratio', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refinedstatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('refined_per', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('refined_forward_per', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('refined_pbr', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('refined_roe', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refinedstatistics')
    op.drop_table('recommandationtickers')
    op.drop_table('rawstatistics')
    # ### end Alembic commands ###
