"""empty message

Revision ID: d02ea383b6f1
Revises: f656d633e40b
Create Date: 2024-04-09 19:18:18.440075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02ea383b6f1'
down_revision: Union[str, None] = 'f656d633e40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawstatistics', sa.Column('averageVolume10days', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('recommandationtickers', sa.Column('averageVolume10days', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('refinedstatistics', sa.Column('averageVolume10days', sa.Numeric(precision=30, scale=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refinedstatistics', 'averageVolume10days')
    op.drop_column('recommandationtickers', 'averageVolume10days')
    op.drop_column('rawstatistics', 'averageVolume10days')
    # ### end Alembic commands ###
