"""empty message

Revision ID: e30768e00ed4
Revises: 80901c81b0c7
Create Date: 2024-03-14 18:41:14.085895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30768e00ed4'
down_revision: Union[str, None] = '80901c81b0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('free_cash_flow', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('repurchase_of_capital_stock', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('repayment_of_debt', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('issuance_of_debt', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('capital_expenditure', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('interest_paid_supplemental_data', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('income_tax_paid_supplemental_data', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('end_cash_position', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('beginning_cash_position', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('effect_of_exchange_rate_changes', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('changes_in_cash', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('financing_cash_flow', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash_flow_from_continuing_financing_activities', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_other_financing_charges', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_common_stock_issuance', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('common_stock_payments', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_issuance_payments_of_debt', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_long_term_debt_issuance', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('long_term_debt_payments', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('long_term_debt_issuance', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('investing_cash_flow', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash_flow_from_continuing_investing_activities', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_other_investing_changes', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_investment_purchase_and_sale', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('sale_of_investment', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('purchase_of_investment', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_business_purchase_and_sale', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('purchase_of_business', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_ppe_purchase_and_sale', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('sale_of_ppe', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('purchase_of_ppe', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('operating_cash_flow', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('cash_flow_from_continuing_operating_activities', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_working_capital', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_other_current_liabilities', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_other_current_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_payables_and_accrued_expense', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_accrued_expense', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_payable', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_account_payable', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_prepaid_assets', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('change_in_receivables', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('changes_in_account_receivables', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('other_non_cash_items', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('stock_based_compensation', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('asset_impairment_charge', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('deferred_tax', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('deferred_income_tax', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('depreciation_amortization_depletion', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('depreciation_and_amortization', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('net_income_from_continuing_operations', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashflows')
    # ### end Alembic commands ###
