"""empty message

Revision ID: e4ef44535ff7
Revises: ea62c8fd2272
Create Date: 2024-03-05 18:54:14.074899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4ef44535ff7'
down_revision: Union[str, None] = 'ea62c8fd2272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.drop_column('question', 'create_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_date', mysql.DATETIME(), nullable=False))
    op.drop_column('question', 'create_at')
    # ### end Alembic commands ###
