"""empty message

Revision ID: f2558e8b0237
Revises: ac92819c70c6
Create Date: 2024-03-12 16:00:01.570800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2558e8b0237'
down_revision: Union[str, None] = 'ac92819c70c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('operating_revenue', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('cost_of_revenue', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('selling_general_and_administrative', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('general_and_administrative_expense', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('other_general_and_administrative', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('research_and_development', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('operating_income', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('net_non_operating_interest_income_expense', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('interest_income_non_operating', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('interest_expense_non_operating', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('total_other_finance_cost', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('other_income_expense', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('gain_on_sale_of_security', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('other_non_operating_income_expenses', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('pretax_income', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('net_income_common_stockholders', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('net_income', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('net_income_including_noncontrolling_interests', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('net_income_continuous_operations', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('average_dilution_earnings', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('diluted_ni_available_to_come_stockholders', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('basic_eps', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('diluted_eps', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('basic_average_shares', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('diluted_average_shares', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('total_operating_income_as_reported', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('net_income_from_continuing_and_discontinued_operation', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('normalized_income', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('interest_income', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('interest_expense', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('net_interest_income', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('ebit', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('reconciled_cost_of_revenue', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('reconciled_depreciation', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('net_income_from_continuing_operation_net_minority_interest', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('total_unusual_items_excluding_goodwill', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('total_unusual_items', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('normalized_ebitda', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('tax_rate_for_calcs', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('tax_effect_of_unusual_items', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.add_column('tickers', sa.Column('industry_code', sa.String(length=100), nullable=False))
    op.drop_column('tickers', 'industryCode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('industryCode', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('tickers', 'industry_code')
    op.drop_table('income_statements')
    # ### end Alembic commands ###
