"""empty message

Revision ID: fcd67441e201
Revises: 1af8972f3dfa
Create Date: 2024-03-31 19:50:21.128863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd67441e201'
down_revision: Union[str, None] = '1af8972f3dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_sheets', sa.Column('total_debt', sa.Numeric(precision=30, scale=10), nullable=False))
    op.add_column('balance_sheets', sa.Column('working_capital', sa.Numeric(precision=30, scale=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_sheets', 'working_capital')
    op.drop_column('balance_sheets', 'total_debt')
    # ### end Alembic commands ###
